'use client';
import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState("ar");

  const translations = {
    en: {
      // Navbar translations
      home: "Home",

      collections: "Collections",
      contacts: "Contacts",
      login: "Login",
      dashboard: "Dashboard",
      cart: "Cart",
      signOut: "Sign Out",
      notifications: "Notifications",
      markAllAsRead: "Mark all as read",
      noNotifications: "No notifications",
      viewAllNotifications: "View all notifications",
      yourCart: "Your Cart",
      clearAll: "Clear All",
      emptyCart: "Your cart is empty",
      emptyCartDesc: "Add some products to get started!",
      browseProducts: "Browse Products",
      total: "Total",
      viewCart: "View Cart",
      switchTo: "Switch to",
     
      // ProductCard translations
      sale: "SALE",
      outOfStock: "OUT OF STOCK",
      sizes: "Sizes",
      more: "more",
      
      // LatestCollections translations
      latestAdditions: "Latest Additions",
      discoverNewest: "Discover our newest collections, products, and categories",
      manageCollections: "Manage Collections",
      collection: "COLLECTION",
      featured: "FEATURED",
      exploreCollection: "Explore Collection",
      products: "Products",
      categories: "Categories",
      season: "Season",
      product: "PRODUCT",
      quickView: "Quick View",
      category: "CATEGORY",
      browse: "Browse",
      viewAllProducts: "View All Products",
      viewAllDesc: "Discover our complete collection of premium fashion and accessories",
      
      // HomepageHero translations
      exteCollection: "Exte Collection",
      timelessElegance: "Timeless elegance redefined",
      discoverNow: "Discover Now",
      
      // Footer translations
      stayInTheKnow: "STAY IN THE KNOW",
      subscribeUpdates: "Subscribe for exclusive updates and early access to new collections",
      enterEmail: "Enter your email",
      subscribe: "SUBSCRIBE",
      brandDescription: "Timeless elegance and contemporary style for the modern individual.",
      help: "HELP",
      customerService: "Customer Service",
      sizeGuide: "Size Guide",
      shipping: "Shipping",
      collections: "COLLECTIONS",
      newArrivals: "New Arrivals",
      bestSellers: "Best Sellers",
      seasonal: "Seasonal",
      company: "COMPANY",
      aboutExet: "About Exet",
      sustainability: "Sustainability",
      careers: "Careers",
      contact: "CONTACT",
      storeLocator: "Store Locator",
      contactUs: "Contact Us",
      press: "Press",
      rightsReserved: "ALL RIGHTS RESERVED.",
      
      // DashboardSidebar translations
      dashboard: "Dashboard",
      userSettings: "User Settings",
      users: "Users",
      cart: "Cart",
      collections: "Collections",
      orders: "Orders",
      likes: "Likes",
      reviews: "Reviews",
      notifications: "Notifications",
      
      // CheckoutForm translations
      checkoutInformation: "CHECKOUT INFORMATION",
      fullName: "FULL NAME *",
      phoneNumber: "PHONE NUMBER *",
      streetAddress: "STREET ADDRESS *",
      city: "CITY *",
      state: "STATE *",
      zipCode: "ZIP CODE *",
      country: "COUNTRY",
      additionalNotes: "ADDITIONAL NOTES (OPTIONAL)",
      orderSummary: "ORDER SUMMARY",
      items: "Items",
      total: "Total",
      cancel: "CANCEL",
      placeOrder: "PLACE ORDER",
      placingOrder: "PLACING ORDER...",

            newestFirst: "Newest First",
      priceLowToHigh: "Price: Low to High",
      priceHighToLow: "Price: High to Low",
      nameAToZ: "Name: A to Z",
      filters: "FILTERS",
      clearAll: "Clear all",
      categories: "CATEGORIES",
      subcategories: "SUBCATEGORIES",
      collections: "COLLECTIONS",
      priceRange: "PRICE RANGE",
      sizes: "SIZES",
      colors: "COLORS",
      applyFilters: "APPLY FILTERS",
      searchProducts: "Search products...",
      found: "found",
      product: "product",
      products: "products",
      category: "Category",
      size: "Size",
      color: "Color",
      noProductsFound: "No products found matching your criteria",
      clearFilters: "CLEAR FILTERS",
      
      // Dashboard
      dashboardFeatures: "Dashboard Features",
      accountManagement: "Account Management",
      restaurantManagement: "Restaurant Management",
      orderTracking: "Order Tracking",
      performanceAnalytics: "Performance Analytics",
      
      // Users Management
      usersManagement: "Users Management",
      welcomeToUsersManagement: "Welcome to users management",
      actions: "Actions",
      updating: "Updating...",
      noUsersFound: "No users found.",
      totalUsers: "TOTAL USERS",
      admins: "ADMINS",
      owners: "OWNERS",
      chefs: "CHEFS",
      waiters: "WAITERS",
      updatingRole: "Updating role...",
      restaurantOwner: "Restaurant Owner",
      chef: "Chef",
      waiter: "Waiter",
      delivery: "Delivery",
      
      // Reviews
      confirmDeleteReview: "Are you sure you want to delete this review?",
      deleteReviewFailed: "Failed to delete review",
      selectRating: "Please select a rating",
      provideTitleOrComment: "Please provide either a title or comment",
      reviewTitle: "Review Title",
      optional: "Optional",
      summarizeExperience: "Summarize your experience...",
      yourReview: "Your Review",
      shareExperience: "Share your experience with this product...",
      characters: "characters",
      submitting: "SUBMITTING...",
      submitReview: "SUBMIT REVIEW",
      noReviewsYet: "You haven't written any reviews yet",
      reviewHelpShoppers: "Review products you've purchased to help other shoppers.",
      orderNumber: "Order #",
      deliveredOn: "Delivered on",
      writeReview: "WRITE REVIEW",
      writeYourReview: "Write Your Review",
      stars: "stars",
      star: "star",
      reviewedOn: "Reviewed on",
      verifiedPurchase: "Verified Purchase",
      submitReviewFailed: "Failed to submit review",
      
      // Performance
      viewPerformanceMetrics: "View your performance metrics",
      salesPerformance: "Sales performance",
      userEngagement: "User engagement",
      revenueAnalytics: "Revenue analytics",
      growthMetrics: "Growth metrics",
      
      // Orders
      allOrders: "ALL ORDERS",
      myOrders: "MY ORDERS",
      noOrdersFound: "No orders found",
      noOrdersYet: "You have no orders yet",
      startShopping: "START SHOPPING",
      placedOn: "Placed on",
      customer: "Customer",
      quantity: "Qty",
      customerInformation: "CUSTOMER INFORMATION",
      name: "Name",
      phone: "Phone",
      address: "Address",
      notes: "Notes",
      olderOrderMessage: "This is an older order. Customer information was not collected at the time of purchase.",
      acceptOrder: "ACCEPT ORDER",
      rejectOrder: "REJECT ORDER",
      markAsShipped: "MARK AS SHIPPED",
      markAsDelivered: "MARK AS DELIVERED",
      updateOrderStatusFailed: "Failed to update order status",
      pending: "PENDING",
      accepted: "ACCEPTED",
      rejected: "REJECTED",
      shipped: "SHIPPED",
      delivered: "DELIVERED",
      notProvided: "Not provided",
      
      // Notifications
      notificationsWillAppear: "Notifications will appear here when you have updates.",
      justNow: "Just now",
      hoursAgo: "h ago",
      daysAgo: "d ago",
      manageNotifications: "Manage your notifications",
      
      // Likes
      signInToViewLikes: "Please sign in to view your liked products.",
      likedProducts: "Liked Products",
      noLikedProducts: "You haven't liked any products yet.",
      likeProductsForLater: "Like products you love to save them for later.",
      removeFromLikesFailed: "Failed to remove from likes",
      
      // Collections Management
      productManagement: "Product Management",
      manageProductsCategories: "Manage products, categories, subcategories, and collections",
      editProduct: "EDIT PRODUCT",
      addNewProduct: "ADD NEW PRODUCT",
      productName: "PRODUCT NAME",
      originalPrice: "ORIGINAL PRICE",
      subcategory: "SUBCATEGORY",
      sizesStock: "SIZES & STOCK",
      selectSize: "Select Size",
      stock: "Stock",
      add: "ADD",
      colorName: "Color Name",
      productImages: "PRODUCT IMAGES",
      uploadProductImages: "UPLOAD PRODUCT IMAGES",
      tagsCommaSeparated: "TAGS (comma separated)",
      featuredProduct: "FEATURED PRODUCT",
      activeProduct: "ACTIVE PRODUCT",
      updatingProduct: "UPDATING PRODUCT...",
      creatingProduct: "CREATING PRODUCT...",
      updateProduct: "UPDATE PRODUCT",
      createProduct: "CREATE PRODUCT",
      active: "Active",
      inactive: "Inactive",
      edit: "Edit",
      delete: "Delete",
      confirmDeleteProduct: "Are you sure you want to delete this product?",
      productDeleted: "Product deleted successfully!",
      deleteProductFailed: "Failed to delete product",
      fetchDataFailed: "Failed to fetch data",
      productImageRequired: "At least one product image is required",
      categoryRequired: "Category is required",
      productUpdated: "Product updated successfully!",
      productCreated: "Product created successfully!",
      updateProductFailed: "Failed to update product",
      createProductFailed: "Failed to create product",
        pleaseSelectSize: "Please select a size",
  productAddedToCart: "Product added to cart!",
  failedToAddToCart: "Failed to add product to cart",
  failedToAddToCartTryAgain: "Failed to add product to cart. Please try again.",
  onlyItemsAvailable: "Only {availableStock} items available in stock for size {selectedSize}",
  onlyItemsAvailableWithCart: "Only {availableStock} items available in stock for size {selectedSize}. You already have {currentInCart} in your cart.",
  insufficientStock: "Insufficient stock available",
  sizeNotAvailable: "Size {size} is not available for this product",
  cartUpdateFailed: "Failed to update cart",
  cartItemNotFound: "Item not found in cart",
  cartNotFound: "Cart not found",
  databaseConnectionFailed: "Database connection failed",
  unauthorizedAccess: "Please login to add items to cart",
  productNotFound: "Product not found",
  requiredFieldsMissing: "Product ID and size are required",
      
      editCategory: "EDIT CATEGORY",
      addNewCategory: "ADD NEW CATEGORY",
      categoryName: "CATEGORY NAME",
      categoryImage: "CATEGORY IMAGE",
      uploadCategoryImage: "UPLOAD CATEGORY IMAGE",
      activeCategory: "ACTIVE CATEGORY",
      updatingCategory: "UPDATING CATEGORY...",
      creatingCategory: "CREATING CATEGORY...",
      updateCategory: "UPDATE CATEGORY",
      createCategory: "CREATE CATEGORY",
      confirmDeleteCategory: "Are you sure you want to delete this category?",
      categoryDeleted: "Category deleted successfully!",
      deleteCategoryFailed: "Failed to delete category",
      categoryUpdated: "Category updated successfully!",
      categoryCreated: "Category created successfully!",
      updateCategoryFailed: "Failed to update category",
      createCategoryFailed: "Failed to create category",
      
      editSubCategory: "EDIT SUBCATEGORY",
      addNewSubCategory: "ADD NEW SUBCATEGORY",
      parentCategory: "PARENT CATEGORY",
      selectParentCategory: "Select Parent Category",
      subCategoryName: "SUBCATEGORY NAME",
      activeSubCategory: "ACTIVE SUBCATEGORY",
      updatingSubCategory: "UPDATING SUBCATEGORY...",
      creatingSubCategory: "CREATING SUBCATEGORY...",
      updateSubCategory: "UPDATE SUBCATEGORY",
      createSubCategory: "CREATE SUBCATEGORY",
      parent: "Parent",
      unknown: "Unknown",
      confirmDeleteSubCategory: "Are you sure you want to delete this subcategory?",
      subCategoryDeleted: "SubCategory deleted successfully!",
      deleteSubCategoryFailed: "Failed to delete subcategory",
      subCategoryUpdated: "SubCategory updated successfully!",
      subCategoryCreated: "SubCategory created successfully!",
      updateSubCategoryFailed: "Failed to update subcategory",
      createSubCategoryFailed: "Failed to create subcategory",
      
      editCollection: "EDIT COLLECTION",
      addNewCollection: "ADD NEW COLLECTION",
      collectionName: "COLLECTION NAME",
      season: "SEASON",
      year: "YEAR",
      collectionImage: "COLLECTION IMAGE",
      uploadCollectionImage: "UPLOAD COLLECTION IMAGE",
      featuredCollection: "FEATURED COLLECTION",
      activeCollection: "ACTIVE COLLECTION",
      updatingCollection: "UPDATING COLLECTION...",
      creatingCollection: "CREATING COLLECTION...",
      updateCollection: "UPDATE COLLECTION",
      createCollection: "CREATE COLLECTION",
      confirmDeleteCollection: "Are you sure you want to delete this collection?",
      collectionDeleted: "Collection deleted successfully!",
      deleteCollectionFailed: "Failed to delete collection",
      collectionUpdated: "Collection updated successfully!",
      collectionCreated: "Collection created successfully!",
      updateCollectionFailed: "Failed to update collection",
      createCollectionFailed: "Failed to create collection",
      
      // Cart
      yourShoppingBag: "YOUR SHOPPING BAG",
      yourBagIsEmpty: "Your bag is empty",
      shoppingBag: "SHOPPING BAG",
      item: "item",
      items: "items",
      each: "each",
      clearShoppingBag: "CLEAR SHOPPING BAG",
      subtotal: "Subtotal",
      cashOnDeliveryNotice: "Currently we only accept",
      cashOnDelivery: "Cash on Delivery",
      proceedToCheckout: "PROCEED TO CHECKOUT",
      freeShippingNotice: "Free shipping on all orders over $50",
      easyReturnsNotice: "Easy returns within 30 days",
      orderPlacedSuccess: "Order placed successfully! You can track your order status in the orders page.",
      placeOrderFailed: "Failed to place order",
      
      // Account
      accountSettings: "Account Settings",
      manageProfileSecurity: "Manage your profile and security preferences",
      profileInformation: "PROFILE INFORMATION",
      changePassword: "CHANGE PASSWORD",
      profilePhoto: "PROFILE PHOTO",
      uploadNewPhoto: "UPLOAD NEW PHOTO",
      imageRecommendations: "Recommended: Square image, at least 400x400 pixels. JPG, PNG, or WebP.",
      personalInformation: "PERSONAL INFORMATION",
      emailAddress: "EMAIL ADDRESS",
      saveChanges: "SAVE CHANGES",
      resetChanges: "RESET CHANGES",
      currentPassword: "CURRENT PASSWORD",
      newPassword: "NEW PASSWORD",
      confirmNewPassword: "CONFIRM NEW PASSWORD",
      passwordRequirements: "Password must be at least 6 characters long. For better security, use a mix of letters, numbers, and symbols.",
      updatePassword: "UPDATE PASSWORD",
      clearFields: "CLEAR FIELDS",
      passwordLengthError: "Password must be at least 6 characters",
      passwordUpdated: "Password updated successfully!",
      updatePasswordFailed: "Failed to update password",

      // Existing translations remain the same...
      map: "Search by map",
      list: "Search by list",
      signIn: "Sign In",
      signOut: "Sign Out",
      addProperty: "Add Property",
      language: "العربية",
      menu: "Menu",
      mobile: "Mobile",
      password: "Password",
      invalidCredentials: "Invalid mobile or password",
      welcome: "Welcome",
      forgotPassword: "Forgot Password?",
      dontHaveAccount: "Don't have an account?",
      signUp: "Sign Up",
      firstName: "First Name",
      lastName: "Last Name",
      confirmPassword: "Confirm Password",
      passwordsDontMatch: "Passwords don't match",
      invalidMobile: "Invalid Syrian mobile number format",
      signupError: "Signup failed",
      networkError: "Network error",
      loading: "Processing...",
      alreadyHaveAccount: "Already have an account?",
      signinAfterSignupFailed: 'Signup successful! Please sign in',
      welcomeBack: "Welcome Back",
      mapView: "Map View",
      satelliteView: "Satellite View",
      governorates: "Syrian Governorates",
      loadingMap: "Loading map...",
      profileSettings: 'Profile Settings',
      mobileNumber: 'Mobile Number',
      profileImage: 'Profile Image URL',
      updateProfile: 'Update Profile',
      profileUpdated: 'Profile updated successfully!',
      updateError: 'Update failed. Please try again.',
      changeImage: 'Change Image',
      imageFormats: 'JPG, PNG up to 5MB',
      uploadError: 'Image upload failed. Please try again.',
      updating: 'Updating...',
      yourProfile: 'Your Profile',
      profileDesc: 'View and edit your personal information',
      manageProfile: 'Manage Profile',
      yourListings: 'Your Listings',
      listingsDesc: 'Manage your property listings',
      viewListings: 'View Listings',
      subscription: 'Subscription',
      subscriptionDesc: 'Manage your subscription plan',
      viewPlan: 'View Plan',
      dashboardDesc: 'Manage your account and listings from here',
      freePlan: 'Free Plan',
      goldenPlan: 'Golden Plan',
      diamondPlan: 'Diamond Plan',
      freePlanDesc: 'Basic features',
      goldenPlanDesc: 'Enhanced visibility',
      diamondPlanDesc: 'Premium experience',
      currentPlan: 'Your Current Plan',
      upgrade: 'Upgrade Now',
      selectPlan: 'Select Plan',
      features: 'Features',
      subscriptionDesc: 'Choose the plan that works best for you. Upgrade or downgrade at any time.',
      liked: 'Liked',
      noLikedProperties: 'You have not liked any properties yet',
      browseProperties: 'Browse Properties',
      viewDetails: 'View Details',
      chat: 'Chats',
      noConversations: 'You have no messages yet',
      markAllRead: 'Mark all as read',
      noNotifications: 'No notifications yet',
      viewAll: 'View all notifications',
      noNotificationsDesc: 'Your notifications will appear here when you have new activity.',
      featuredListings: 'Featured Listings',
      allListings: 'All Listings',
      viewAllProperties: 'View All Properties',
      bedrooms: 'Bedrooms',
      bathrooms: 'Bathrooms',
      area: 'Area',
      apartments: 'Apartments',
      villas: 'Villas',
      commercial: 'Commercial',
      land: 'Land',
      allProperties: 'All Properties',
      propertyImages: 'Add Images for the property',
      loadMore: 'Load More',
      title: 'Property Title',
      price: 'Property Price',
      location: 'Property Address',
      propertyType: 'Property Type',
      apartment: 'Apartment',
      villa: 'Villa',
      office: 'Office',
      description: 'Description',
      minPrice: "Min Price",
      maxPrice: "Max Price",
      any: "Any",
      featuredOnly: "Featured Only",
      resetFilters: "Reset Filters",
      noImage: "No Image",
      noPropertiesFound: "No properties found",
      clearFilters: "Clear Filters",
      bedroom: "Bed",
      bathrooms: "Baths",
      filterListings: "Filter Listings",
      loginRequired: "Login Required",
      loginToViewListings: "Please log in to view all property listings",
      loginToSeeMore: "Log in to see all available properties",
      featuredSample: "Featured Property Sample",
      contractType: "Contract Type",
      rent: "Rent",
      sale: "Sale",
      mortgage: "Mortgage",
      ownershipType: "Ownership Type",
      green_deed: "Green Deed (طابو أخضر)",
      white_deed: "White Deed (طابو أبيض)",
      court_decision: "Court Decision (حكم محكمة)",
      notary: "Notary (كاتب عدل)",
      emiri: "Emiri (أميري)",
      reform: "Reform (إصلاح)",
      charitable_endowment: "Charitable Endowment (وقف خيري)",
      lineage_endowment: "Lineage Endowment (وقف ذري)",
      meter: 'm²',
      governorate: "Governorate",
      city: "City",
      district: "District",
      selectGovernorate: "Select Governorate",
      selectCity: "Select City",
      selectDistrict: "Select District",
      locationDetails: "Location Details",
      pdetails: 'Property Details',
      propertyAge: "Property Age",
      airConditioning: "Air Conditioning",
      privateParking: "Private Parking",
      entrances: "Number of Entrances",
      electricity: "Electricity",
      water: "Water",
      violations: "Violations Exist",
      rooftopOwnership: "Rooftop Ownership",
      video: "Property Video",
      yes: "Yes",
      no: "No",
      none: "None",
      normalSplit: "Normal Split AC",
      inverterSplit: "Inverter Split AC",
      central: "Central AC",
      concealed: "Concealed AC",
      windowAC: "Window AC",
      desertAC: "Desert AC",
      noElectricity: "No Electricity",
      solarPanels: "Solar Panels",
      amberSubscription: "Amber Subscription",
      govElectricity: "Government Electricity",
      noWater: "No Water",
      nonDrinkable: "Non-Drinkable",
      drinkable: "Drinkable",
      shared: "Shared",
      private: "Private",
      videoUploadError: "Failed to upload video",
    },
    ar: {
      // Navbar translations
      home: "الرئيسية",
            email:"البريد الالكتروني",
      collections: "المجموعات",
      contacts: "اتصل بنا",
      login: "تسجيل الدخول",
      dashboard: "لوحة التحكم",
      cart: "عربة التسوق",
      signOut: "تسجيل الخروج",
      notifications: "الإشعارات",
      markAllAsRead: "تحديد الكل كمقروء",
      noNotifications: "لا توجد إشعارات",
      viewAllNotifications: "عرض جميع الإشعارات",
      yourCart: "عربة التسوق",
      clearAll: "مسح الكل",
      emptyCart: "عربة التسوق فارغة",
      emptyCartDesc: "أضف بعض المنتجات للبدء!",
      browseProducts: "تصفح المنتجات",
      total: "المجموع",
      viewCart: "عرض العربة",
      switchTo: "التغيير إلى",
      
      // ProductCard translations
      sale: "تخفيض",
      outOfStock: "غير متوفر",
      sizes: "المقاسات",
      more: "المزيد",
      
      // LatestCollections translations
      latestAdditions: "أحدث الإضافات",
      discoverNewest: "اكتشف أحدث مجموعاتنا ومنتجاتنا وفئاتنا",
      manageCollections: "إدارة المجموعات",
      collection: "مجموعة",
      featured: "مميز",
      exploreCollection: "استكشف المجموعة",
      products: "المنتجات",
      categories: "الفئات",
      season: "الموسم",
      product: "منتج",
      quickView: "عرض سريع",
      category: "فئة",
      browse: "تصفح",
      viewAllProducts: "عرض جميع المنتجات",
      viewAllDesc: "اكتشف مجموعتنا الكاملة من الأزياء والإكسسوارات الفاخرة",
      
      // HomepageHero translations
      exteCollection: "مجموعة إكستي",
      timelessElegance: "أناقة خالدة مع تعريف جديد",
      discoverNow: "اكتشف الآن",
      
      // Footer translations
      stayInTheKnow: "ابق على اطلاع",
      subscribeUpdates: "اشترك للحصول على تحديثات حصرية ووصول مبكر للمجموعات الجديدة",
      enterEmail: "أدخل بريدك الإلكتروني",
      subscribe: "اشتراك",
      brandDescription: "أناقة خالدة وأسلوب معاصر للفرد العصري.",
      help: "المساعدة",
      customerService: "خدمة العملاء",
      sizeGuide: "دليل المقاسات",
      shipping: "الشحن",
      collections: "المجموعات",
      newArrivals: "الوافدون الجدد",
      bestSellers: "الأكثر مبيعاً",
      seasonal: "الموسمية",
      company: "الشركة",
      aboutExet: "عن إكست",
      sustainability: "الاستدامة",
      careers: "الوظائف",
      contact: "اتصل بنا",
      storeLocator: "مواقع المتاجر",
      contactUs: "اتصل بنا",
      press: "الصحافة",
      rightsReserved: "جميع الحقوق محفوظة.",
      
      // DashboardSidebar translations
      dashboard: "لوحة التحكم",
      userSettings: "إعدادات المستخدم",
      users: "المستخدمين",
      cart: "عربة التسوق",
      collections: "المجموعات",
      orders: "الطلبات",
      likes: "الإعجابات",
      reviews: "التقييمات",
      notifications: "الإشعارات",
      
      // CheckoutForm translations
      checkoutInformation: "معلومات الدفع",
      fullName: "الاسم الكامل *",
      phoneNumber: "رقم الهاتف *",
      streetAddress: "عنوان الشارع *",
      city: "المدينة *",
      state: "الولاية *",
      zipCode: "الرمز البريدي *",
      country: "الدولة",
      additionalNotes: "ملاحظات إضافية (اختياري)",
      orderSummary: "ملخص الطلب",
      items: "المنتجات",
      total: "المجموع",
      cancel: "إلغاء",
      placeOrder: "تقديم الطلب",
      placingOrder: "جاري تقديم الطلب...",

      // Existing Arabic translations remain the same...
            signIn: "تسجيل الدخول",
              pleaseSelectSize: "يرجى اختيار مقاس",
  productAddedToCart: "تمت إضافة المنتج إلى السلة!",
  failedToAddToCart: "فشل إضافة المنتج إلى السلة",
  failedToAddToCartTryAgain: "فشل إضافة المنتج إلى السلة. يرجى المحاولة مرة أخرى.",
  onlyItemsAvailable: "فقط {availableStock} قطعة متوفرة في المخزون للمقاس {selectedSize}",
  onlyItemsAvailableWithCart: "فقط {availableStock} قطعة متوفرة في المخزون للمقاس {selectedSize}. لديك بالفعل {currentInCart} في سلة التسوق.",
  insufficientStock: "لا يوجد مخزون كافي",
  sizeNotAvailable: "المقاس {size} غير متوفر لهذا المنتج",
  cartUpdateFailed: "فشل تحديث سلة التسوق",
  cartItemNotFound: "المنتج غير موجود في السلة",
  cartNotFound: "لم يتم العثور على سلة التسوق",
  databaseConnectionFailed: "فشل الاتصال بقاعدة البيانات",
  unauthorizedAccess: "يرجى تسجيل الدخول لإضافة منتجات إلى السلة",
  productNotFound: "المنتج غير موجود",
  requiredFieldsMissing: "معرف المنتج والمقاس مطلوبان",
      signOut: "تسجيل الخروج",
      language: "English",
      menu: "القائمة",
      mobile: "رقم الجوال",
      password: "كلمة المرور",
      invalidCredentials: "رقم الجوال أو كلمة المرور غير صحيحة",
      welcome: "مرحباً",
      forgotPassword: "نسيت كلمة المرور؟",
      dontHaveAccount: "ليس لديك حساب؟",
      signUp: "تسجيل",
      firstName: "الاسم الأول",
      lastName: "الاسم الأخير",
      confirmPassword: "تأكيد كلمة المرور",
      passwordsDontMatch: "كلمات المرور غير متطابقة",
      invalidMobile: "صيغة رقم الجوال السوري غير صالحة",
      signupError: "فشل إنشاء الحساب",
      networkError: "خطأ في الشبكة",
      loading: "جاري المعالجة...",
      alreadyHaveAccount: "هل لديك حساب بالفعل؟",
      signinAfterSignupFailed: 'تم التسجيل بنجاح! يرجى تسجيل الدخول',
      welcomeBack: "أهلا بك يا ",
      mapView: "عرض الخريطة",
      satelliteView: "عرض الأقمار الصناعية",
      governorates: "المحافظات السورية",
      loadingMap: "جاري تحميل الخريطة...",
      profileSettings: 'إعدادات الملف الشخصي',
      mobileNumber: 'رقم الهاتف',
      profileImage: 'رابط صورة الملف الشخصي',
      updateProfile: 'تحديث الملف الشخصي',
      profileUpdated: 'تم تحديث الملف الشخصي بنجاح!',
      updateError: 'فشل التحديث. يرجى المحاولة مرة أخرى.',
      changeImage: 'تغيير الصورة',
      imageFormats: 'JPG, PNG بحد أقصى 5MB',
      uploadError: 'فشل تحميل الصورة. يرجى المحاولة مرة أخرى.',
      updating: 'جارٍ التحديث...',
      yourProfile: 'ملفك الشخصي',
      profileDesc: 'عرض وتعديل معلوماتك الشخصية',
      manageProfile: 'إدارة الملف',
      yourListings: 'عقاراتك',
      listingsDesc: 'إدارة قوائم العقارات الخاصة بك',
      viewListings: 'عرض العقارات',
      subscription: 'الاشتراك',
      subscriptionDesc: 'إدارة خطة الاشتراك الخاصة بك',
      viewPlan: 'عرض الخطة',
      dashboardDesc: 'ادخل حسابك وعقاراتك من هنا',
      freePlan: 'الباقة المجانية',
      goldenPlan: 'الباقة الذهبية',
      diamondPlan: 'الباقة الماسية',
      freePlanDesc: 'ميزات أساسية',
      goldenPlanDesc: 'ظهور مميز',
      diamondPlanDesc: 'تجربة مميزة',
      currentPlan: 'باقتك الحالية',
      upgrade: 'ترقية الآن',
      selectPlan: 'اختر الباقة',
      features: 'المميزات',
      subscriptionDesc: 'اختر الباقة التي تناسبك. يمكنك الترقية أو التخفيض في أي وقت.',
      liked: 'المفضلة',
      noLikedProperties: 'لم تقم بإضافة أي عقارات إلى المفضلة بعد',
      browseProperties: 'تصفح العقارات',
      viewDetails: 'عرض التفاصيل',
      chat: ' المحادثات',
      noConversations: 'لا توجد لديك أي محادثات بعد',
      markAllRead: 'تحديد الكل كمقروء',
      noNotifications: 'لا توجد إشعارات بعد',
      viewAll: 'عرض جميع الإشعارات',
      noNotificationsDesc: 'ستظهر إشعاراتك هنا عندما يكون لديك نشاط جديد.',
      featuredListings: 'العروض المميزة',
      allListings: 'جميع العقارات',
      viewAllProperties: 'عرض جميع العقارات',
      bedrooms: 'غرف النوم',
      bathrooms: 'الحمامات',
      area: 'المساحة بالمتر المربع (م²)',
      apartments: 'شقق',
      villa: 'فيلا',
      shop: 'محل',
      office: 'مكتب',
      full_floor: 'طابق كامل',
      full_building: 'مبنى كامل',
      house: 'بيت',
      arabian_house: 'بيت عربي',
      farm: 'مزرعة',
      warehouse: 'مستودع',
      seaside_chalet: 'شاليه على البحر',
      palace: 'قصر',
      showroom: 'معرض',
      wedding_hall: 'قاعة افراح',
      land: 'أرض',
      allProperties: 'جميع العقارات',
      propertyImage: 'صورة العقار',
      loadMore: 'تحميل المزيد',
      title: 'اسم العقار',
      price: 'سعر العقار',
      location: ' عنوان العقار بالتفصيل',
      propertyType: 'نوع العقار',
      apartment: 'شقة',
      description: 'وصف العقار',
      minPrice: "أقل سعر",
      maxPrice: "أعلى سعر",
      any: "أي",
      featuredOnly: "المميزة فقط",
      resetFilters: "إعادة تعيين الفلاتر",
      noImage: "لا توجد صورة",
      noPropertiesFound: "لم يتم العثور على عقارات",
      clearFilters: "مسح الفلاتر",
      bedroom: "غرفة",
      bathrooms: "دورات المياه",
      filterListings: "تصفية القوائم",
      loginRequired: "تسجيل الدخول مطلوب",
      loginToViewListings: "يرجى تسجيل الدخول لعرض جميع قوائم العقارات",
      loginToSeeMore: "سجل الدخول لرؤية جميع العقارات المتاحة",
      featuredSample: "عقار مميز كمثال",
      contractType: "نوع العقد",
      rent: "إيجار",
      sale: "بيع",
      mortgage: "رهن",
      ownershipType: "نوع الملكية",
      green_deed: "طابو أخضر",
      white_deed: "طابو أبيض",
      court_decision: "حكم محكمة",
      notary: "كاتب عدل",
      emiri: "أميري",
      reform: "إصلاح",
      charitable_endowment: "وقف خيري",
      lineage_endowment: "وقف ذري",
      verifiedOnly: 'عقار موثق فقط',
      meter: 'م²',
      governorate: "المحافظة",
      city: "المدينة",
      district: "المنطقة",
      selectGovernorate: "اختر المحافظة",
      selectCity: "اختر المدينة",
      selectDistrict: "اختر المنطقة",
      locationDetails: "تفاصيل الموقع",
      propertyImages: 'صور العقار',
      max10Images: 'الحد الأعلى 10 صور',
      uploadImages: 'تحميل صور العقار',
      image: 'اضافة صور للعقار',
      noImages: 'لم يتم اضافة صور للعقار',
      coordinates: 'احداثيات العقار',
      selectLocation: 'قم باختيار موقع العقار الحغرافي',
      clickToPlace: 'اضغط على الخريطة لاختيار موقع العقار',
      pdetails: 'تفاصيل العقار',
      propertyAge: "عمر العقار",
      airConditioning: "المكيفات",
      privateParking: "موقف سيارات خاص",
      entrances: "عدد مداخل البيت",
      electricity: "الكهرباء",
      water: "المياه",
      violations: "هل يوجد مخالفات على العقار",
      rooftopOwnership: "ملكية سطح العقار",
      video: "فيديو العقار",
      yes: "نعم",
      no: "لا",
      none: "لا يوجد",
      normalSplit: "سبليت عادي",
      inverterSplit: "سبليت إنفرتر",
      central: "مركزي",
      concealed: "مخفي",
      windowAC: "نافذة",
      desertAC: "صحراوي",
      noElectricity: "لا يوجد كهرباء",
      solarPanels: "طاقة شمسية",
      amberSubscription: "اشتراك أمبير",
      govElectricity: "كهرباء حكومية فقط",
      noWater: "لا يوجد مياه",
      nonDrinkable: "غير صالحة للشرب",
      drinkable: "صالحة للشرب",
      shared: "مشتركة",
      private: "خاصة",
      videoUploadError: "فشل تحميل الفيديو",

      newestFirst: "الأحدث أولاً",
      priceLowToHigh: "السعر: من الأقل إلى الأعلى",
      priceHighToLow: "السعر: من الأعلى إلى الأقل",
      nameAToZ: "الاسم: من أ إلى ي",
      filters: "الفلاتر",
      clearAll: "مسح الكل",
      categories: "الفئات",
      subcategories: "الفئات الفرعية",
      collections: "المجموعات",
      priceRange: "نطاق السعر",
      sizes: "المقاسات",
      colors: "الألوان",
      applyFilters: "تطبيق الفلاتر",
      searchProducts: "ابحث عن المنتجات...",
      found: "تم العثور على",
      product: "منتج",
      products: "منتجات",
      category: "الفئة",
      size: "المقاس",
      color: "اللون",
      noProductsFound: "لم يتم العثور على منتجات تطابق معاييرك",
      clearFilters: "مسح الفلاتر",
      
      // Dashboard
      dashboardFeatures: "مميزات لوحة التحكم",
      accountManagement: "إدارة الحساب",
      restaurantManagement: "إدارة المطعم",
      orderTracking: "تتبع الطلبات",
      performanceAnalytics: "تحليلات الأداء",
      
      // Users Management
      usersManagement: "إدارة المستخدمين",
      welcomeToUsersManagement: "مرحباً بك في إدارة المستخدمين",
      actions: "الإجراءات",
      updating: "جارٍ التحديث...",
      noUsersFound: "لم يتم العثور على مستخدمين.",
      totalUsers: "إجمالي المستخدمين",
      admins: "المسؤولون",
      owners: "المالكون",
      chefs: "الطهاة",
      waiters: "النُدُل",
      updatingRole: "جارٍ تحديث الدور...",
      restaurantOwner: "مالك المطعم",
      chef: "طاهي",
      waiter: "نادل",
      delivery: "توصيل",
      
      // Reviews
      confirmDeleteReview: "هل أنت متأكد أنك تريد حذف هذا التقييم؟",
      deleteReviewFailed: "فشل حذف التقييم",
      selectRating: "يرجى اختيار تقييم",
      provideTitleOrComment: "يرجى تقديم عنوان أو تعليق",
      reviewTitle: "عنوان التقييم",
      optional: "اختياري",
      summarizeExperience: "لخص تجربتك...",
      yourReview: "تقييمك",
      shareExperience: "شارك تجربتك مع هذا المنتج...",
      characters: "حرف",
      submitting: "جارٍ الإرسال...",
      submitReview: "إرسال التقييم",
      noReviewsYet: "لم تقم بكتابة أي تقييمات بعد",
      reviewHelpShoppers: "قيم المنتجات التي اشتريتها لمساعدة المتسوقين الآخرين.",
      orderNumber: "طلب رقم",
      deliveredOn: "تم التوصيل في",
      writeReview: "كتابة تقييم",
      writeYourReview: "اكتب تقييمك",
      stars: "نجوم",
      star: "نجمة",
      reviewedOn: "تم التقييم في",
      verifiedPurchase: "شراء موثق",
      submitReviewFailed: "فشل إرسال التقييم",
      
      // Performance
      viewPerformanceMetrics: "عرض مقاييس أدائك",
      salesPerformance: "أداء المبيعات",
      userEngagement: "تفاعل المستخدم",
      revenueAnalytics: "تحليلات الإيرادات",
      growthMetrics: "مقاييس النمو",
      
      // Orders
      allOrders: "جميع الطلبات",
      myOrders: "طلباتي",
      noOrdersFound: "لم يتم العثور على طلبات",
      noOrdersYet: "ليس لديك أي طلبات بعد",
      startShopping: "ابدأ التسوق",
      placedOn: "تم الطلب في",
      customer: "العميل",
      quantity: "الكمية",
      customerInformation: "معلومات العميل",
      name: "الاسم",
      phone: "الهاتف",
      address: "العنوان",
      notes: "ملاحظات",
      olderOrderMessage: "هذا طلب قديم. لم يتم جمع معلومات العميل في وقت الشراء.",
      acceptOrder: "قبول الطلب",
      rejectOrder: "رفض الطلب",
      markAsShipped: "تعيين كشحن",
      markAsDelivered: "تعيين كموصل",
      updateOrderStatusFailed: "فشل تحديث حالة الطلب",
      pending: "قيد الانتظار",
      accepted: "مقبول",
      rejected: "مرفوض",
      shipped: "تم الشحن",
      delivered: "تم التوصيل",
      notProvided: "غير مقدم",
      
      // Notifications
      notificationsWillAppear: "ستظهر الإشعارات هنا عندما يكون لديك تحديثات.",
      justNow: "الآن",
      hoursAgo: "ساعة مضت",
      daysAgo: "يوم مضى",
      manageNotifications: "إدارة إشعاراتك",
      
      // Likes
      signInToViewLikes: "يرجى تسجيل الدخول لعرض المنتجات المفضلة.",
      likedProducts: "المنتجات المفضلة",
      noLikedProducts: "لم تقم بإضافة أي منتجات إلى المفضلة بعد.",
      likeProductsForLater: "أضف المنتجات التي تحبها إلى المفضلة لحفظها لوقت لاحق.",
      removeFromLikesFailed: "فشل إزالة من المفضلة",
      
      // Collections Management
      productManagement: "إدارة المنتجات",
      manageProductsCategories: "إدارة المنتجات والفئات والفئات الفرعية والمجموعات",
      editProduct: "تعديل المنتج",
      addNewProduct: "إضافة منتج جديد",
      productName: "اسم المنتج",
      originalPrice: "السعر الأصلي",
      subcategory: "الفئة الفرعية",
      sizesStock: "المقاسات والمخزون",
      selectSize: "اختر المقاس",
      stock: "المخزون",
      add: "إضافة",
      colorName: "اسم اللون",
      productImages: "صور المنتج",
      uploadProductImages: "رفع صور المنتج",
      tagsCommaSeparated: "الوسوم (مفصولة بفواصل)",
      featuredProduct: "منتج مميز",
      activeProduct: "منتج نشط",
      updatingProduct: "جارٍ تحديث المنتج...",
      creatingProduct: "جارٍ إنشاء المنتج...",
      updateProduct: "تحديث المنتج",
      createProduct: "إنشاء المنتج",
      active: "نشط",
      inactive: "غير نشط",
      edit: "تعديل",
      delete: "حذف",
      confirmDeleteProduct: "هل أنت متأكد أنك تريد حذف هذا المنتج؟",
      productDeleted: "تم حذف المنتج بنجاح!",
      deleteProductFailed: "فشل حذف المنتج",
      fetchDataFailed: "فشل جلب البيانات",
      productImageRequired: "مطلوب صورة واحدة على الأقل للمنتج",
      categoryRequired: "الفئة مطلوبة",
      productUpdated: "تم تحديث المنتج بنجاح!",
      productCreated: "تم إنشاء المنتج بنجاح!",
      updateProductFailed: "فشل تحديث المنتج",
      createProductFailed: "فشل إنشاء المنتج",
      
      editCategory: "تعديل الفئة",
      addNewCategory: "إضافة فئة جديدة",
      categoryName: "اسم الفئة",
      categoryImage: "صورة الفئة",
      uploadCategoryImage: "رفع صورة الفئة",
      activeCategory: "فئة نشطة",
      updatingCategory: "جارٍ تحديث الفئة...",
      creatingCategory: "جارٍ إنشاء الفئة...",
      updateCategory: "تحديث الفئة",
      createCategory: "إنشاء الفئة",
      confirmDeleteCategory: "هل أنت متأكد أنك تريد حذف هذه الفئة؟",
      categoryDeleted: "تم حذف الفئة بنجاح!",
      deleteCategoryFailed: "فشل حذف الفئة",
      categoryUpdated: "تم تحديث الفئة بنجاح!",
      categoryCreated: "تم إنشاء الفئة بنجاح!",
      updateCategoryFailed: "فشل تحديث الفئة",
      createCategoryFailed: "فشل إنشاء الفئة",
      
      editSubCategory: "تعديل الفئة الفرعية",
      addNewSubCategory: "إضافة فئة فرعية جديدة",
      parentCategory: "الفئة الأم",
      selectParentCategory: "اختر الفئة الأم",
      subCategoryName: "اسم الفئة الفرعية",
      activeSubCategory: "فئة فرعية نشطة",
      updatingSubCategory: "جارٍ تحديث الفئة الفرعية...",
      creatingSubCategory: "جارٍ إنشاء الفئة الفرعية...",
      updateSubCategory: "تحديث الفئة الفرعية",
      createSubCategory: "إنشاء الفئة الفرعية",
      parent: "الأم",
      unknown: "غير معروف",
      confirmDeleteSubCategory: "هل أنت متأكد أنك تريد حذف هذه الفئة الفرعية؟",
      subCategoryDeleted: "تم حذف الفئة الفرعية بنجاح!",
      deleteSubCategoryFailed: "فشل حذف الفئة الفرعية",
      subCategoryUpdated: "تم تحديث الفئة الفرعية بنجاح!",
      subCategoryCreated: "تم إنشاء الفئة الفرعية بنجاح!",
      updateSubCategoryFailed: "فشل تحديث الفئة الفرعية",
      createSubCategoryFailed: "فشل إنشاء الفئة الفرعية",
      
      editCollection: "تعديل المجموعة",
      addNewCollection: "إضافة مجموعة جديدة",
      collectionName: "اسم المجموعة",
      season: "الموسم",
      year: "السنة",
      collectionImage: "صورة المجموعة",
      uploadCollectionImage: "رفع صورة المجموعة",
      featuredCollection: "مجموعة مميزة",
      activeCollection: "مجموعة نشطة",
      updatingCollection: "جارٍ تحديث المجموعة...",
      creatingCollection: "جارٍ إنشاء المجموعة...",
      updateCollection: "تحديث المجموعة",
      createCollection: "إنشاء المجموعة",
      confirmDeleteCollection: "هل أنت متأكد أنك تريد حذف هذه المجموعة؟",
      collectionDeleted: "تم حذف المجموعة بنجاح!",
      deleteCollectionFailed: "فشل حذف المجموعة",
      collectionUpdated: "تم تحديث المجموعة بنجاح!",
      collectionCreated: "تم إنشاء المجموعة بنجاح!",
      updateCollectionFailed: "فشل تحديث المجموعة",
      createCollectionFailed: "فشل إنشاء المجموعة",
      
      // Cart
      yourShoppingBag: "حقيبة التسوق الخاصة بك",
      yourBagIsEmpty: "حقيبتك فارغة",
      shoppingBag: "حقيبة التسوق",
      item: "قطعة",
      items: "قطع",
      each: "لكل",
      clearShoppingBag: "تفريغ حقيبة التسوق",
      subtotal: "المجموع الفرعي",
      cashOnDeliveryNotice: "حالياً نقبل فقط",
      cashOnDelivery: "الدفع عند الاستلام",
      proceedToCheckout: "المتابعة للدفع",
      freeShippingNotice: "شحن مجاني لجميع الطلبات فوق 50$",
      easyReturnsNotice: "إرجاع سهل خلال 30 يوم",
      orderPlacedSuccess: "تم تقديم الطلب بنجاح! يمكنك تتبع حالة طلبك في صفحة الطلبات.",
      placeOrderFailed: "فشل تقديم الطلب",
      
      // Account
      accountSettings: "إعدادات الحساب",
      manageProfileSecurity: "إدارة ملفك الشخصي وتفضيلات الأمان",
      profileInformation: "معلومات الملف الشخصي",
      changePassword: "تغيير كلمة المرور",
      profilePhoto: "صورة الملف الشخصي",
      uploadNewPhoto: "رفع صورة جديدة",
      imageRecommendations: "مستحسن: صورة مربعة، 400x400 بكسل على الأقل. JPG, PNG, أو WebP.",
      personalInformation: "المعلومات الشخصية",
      emailAddress: "عنوان البريد الإلكتروني",
      saveChanges: "حفظ التغييرات",
      resetChanges: "إعادة التعيين",
      currentPassword: "كلمة المرور الحالية",
      newPassword: "كلمة المرور الجديدة",
      confirmNewPassword: "تأكيد كلمة المرور الجديدة",
      passwordRequirements: "يجب أن تكون كلمة المرور 6 أحرف على الأقل. لأمان أفضل، استخدم مزيجاً من الحروف والأرقام والرموز.",
      updatePassword: "تحديث كلمة المرور",
      clearFields: "مسح الحقول",
      passwordLengthError: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
      passwordUpdated: "تم تحديث كلمة المرور بنجاح!",
      updatePasswordFailed: "فشل تحديث كلمة المرور",
       productNotFound: "المنتج غير موجود",
  backToProducts: "العودة إلى المنتجات",
  noImageAvailable: "لا توجد صورة متاحة",
  description: "الوصف",
  color: "اللون",
  size: "المقاس",
  sizeGuide: "دليل المقاسات",
  quantity: "الكمية",
  addToCart: "أضف إلى السلة",
  outOfStock: "غير متوفر",
  like: "أعجبني",
  liked: "معجب به",
  likes: "إعجابات",
  sku: "رمز المنتج",
  category: "الفئة",
  subcategory: "الفئة الفرعية",
  collection: "المجموعة",
  youMightAlsoLike: "قد يعجبك أيضاً",
  customerReviews: "تقييمات العملاء",
  noReviewsYet: "لا توجد تقييمات بعد",
  beFirstToReview: "كن أول من يقيم هذا المنتج!",
  writeReview: "كتابة تقييم",
  reviewBy: "تقييم بواسطة",
  verifiedPurchase: "شراء موثق",
  by: "بواسطة",
  helpful: "مفيد",
  pleaseSelectSize: "يرجى اختيار مقاس",
  productAddedToCart: "تمت إضافة المنتج إلى السلة!",
  failedToAddToCart: "فشل إضافة المنتج إلى السلة",
  failedToAddToCartTryAgain: "فشل إضافة المنتج إلى السلة. يرجى المحاولة مرة أخرى.",
  save: "وفر",
  review: "تقييم",
  reviews: "تقييمات",
  accountSettings:"اعدادات الحساب",
  hasDiscount: 'هل عليه تخفيض ؟',
discountPrice: 'السعر بعد التخفيض',
  // Add these to the 'ar' object in your LanguageContext.js

// From account/page.js
profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
updateProfileFailed: "فشل تحديث الملف الشخصي",
networkError: "حدث خطأ في الشبكة",
passwordsDontMatch: "كلمات المرور الجديدة غير متطابقة",
passwordLengthError: "يجب أن تكون كلمة المرور 6 أحرف على الأقل",
passwordUpdated: "تم تحديث كلمة المرور بنجاح!",
updatePasswordFailed: "فشل تحديث كلمة المرور",
imageUploaded: "تم تحميل الصورة بنجاح!",
accountSettings: "إعدادات الحساب",
manageProfileSecurity: "إدارة ملفك الشخصي وتفضيلات الأمان",
profileInformation: "معلومات الملف الشخصي",
changePassword: "تغيير كلمة المرور",
profilePhoto: "صورة الملف الشخصي",
uploadNewPhoto: "رفع صورة جديدة",
imageRecommendations: "مستحسن: صورة مربعة، 400x400 بكسل على الأقل. JPG, PNG, أو WebP.",
personalInformation: "المعلومات الشخصية",
firstName: "الاسم الأول",
lastName: "الاسم الأخير",
emailAddress: "عنوان البريد الإلكتروني",
saveChanges: "حفظ التغييرات",
resetChanges: "إعادة التعيين",
currentPassword: "كلمة المرور الحالية",
newPassword: "كلمة المرور الجديدة",
confirmNewPassword: "تأكيد كلمة المرور الجديدة",
passwordRequirements: "يجب أن تكون كلمة المرور 6 أحرف على الأقل. لأمان أفضل، استخدم مزيجاً من الحروف والأرقام والرموز.",
updatePassword: "تحديث كلمة المرور",
clearFields: "مسح الحقول",
updating: "جارٍ التحديث...",

// From cart/page.js
yourShoppingBag: "حقيبة التسوق الخاصة بك",
yourBagIsEmpty: "حقيبتك فارغة",
continueShopping: "مواصلة التسوق",
shoppingBag: "حقيبة التسوق",
item: "قطعة",
items: "قطع",
noImage: "لا توجد صورة",
size: "المقاس",
color: "اللون",
quantity: "الكمية",
each: "لكل",
clearShoppingBag: "تفريغ حقيبة التسوق",
orderSummary: "ملخص الطلب",
subtotal: "المجموع الفرعي",
total: "المجموع",
cashOnDeliveryNotice: "حالياً نقبل فقط",
cashOnDelivery: "الدفع عند الاستلام",
proceedToCheckout: "المتابعة للدفع",
freeShippingNotice: "شحن مجاني لجميع الطلبات فوق 50$",
easyReturnsNotice: "إرجاع سهل خلال 30 يوم",
orderPlacedSuccess: "تم تقديم الطلب بنجاح! يمكنك تتبع حالة طلبك في صفحة الطلبات.",
placeOrderFailed: "فشل تقديم الطلب",

// From collections/page.js
productManagement: "إدارة المنتجات",
manageProductsCategories: "إدارة المنتجات والفئات والفئات الفرعية والمجموعات",
editProduct: "تعديل المنتج",
addNewProduct: "إضافة منتج جديد",
productName: "اسم المنتج",
description: "الوصف",
price: "السعر",
originalPrice: "السعر الأصلي",
category: "الفئة",
subCategory: "الفئة الفرعية",
collection: "المجموعة",
sizesStock: "المقاسات والمخزون",
selectSize: "اختر المقاس",
stock: "المخزون",
add: "إضافة",
colorName: "اسم اللون",
productImages: "صور المنتج",
uploadProductImages: "رفع صور المنتج",
tagsCommaSeparated: "الوسوم (مفصولة بفواصل)",
featuredProduct: "منتج مميز",
activeProduct: "منتج نشط",
updatingProduct: "جارٍ تحديث المنتج...",
creatingProduct: "جارٍ إنشاء المنتج...",
updateProduct: "تحديث المنتج",
createProduct: "إنشاء المنتج",
products: "المنتجات",
active: "نشط",
inactive: "غير نشط",
edit: "تعديل",
delete: "حذف",
confirmDeleteProduct: "هل أنت متأكد أنك تريد حذف هذا المنتج؟",
productDeleted: "تم حذف المنتج بنجاح!",
deleteProductFailed: "فشل حذف المنتج",
fetchDataFailed: "فشل جلب البيانات",
productImageRequired: "مطلوب صورة واحدة على الأقل للمنتج",
categoryRequired: "الفئة مطلوبة",
productUpdated: "تم تحديث المنتج بنجاح!",
productCreated: "تم إنشاء المنتج بنجاح!",
updateProductFailed: "فشل تحديث المنتج",
createProductFailed: "فشل إنشاء المنتج",

editCategory: "تعديل الفئة",
addNewCategory: "إضافة فئة جديدة",
categoryName: "اسم الفئة",
categoryImage: "صورة الفئة",
uploadCategoryImage: "رفع صورة الفئة",
activeCategory: "فئة نشطة",
updatingCategory: "جارٍ تحديث الفئة...",
creatingCategory: "جارٍ إنشاء الفئة...",
updateCategory: "تحديث الفئة",
createCategory: "إنشاء الفئة",
categories: "الفئات",
confirmDeleteCategory: "هل أنت متأكد أنك تريد حذف هذه الفئة؟",
categoryDeleted: "تم حذف الفئة بنجاح!",
deleteCategoryFailed: "فشل حذف الفئة",
categoryUpdated: "تم تحديث الفئة بنجاح!",
categoryCreated: "تم إنشاء الفئة بنجاح!",
updateCategoryFailed: "فشل تحديث الفئة",
createCategoryFailed: "فشل إنشاء الفئة",

editSubCategory: "تعديل الفئة الفرعية",
addNewSubCategory: "إضافة فئة فرعية جديدة",
parentCategory: "الفئة الأم",
selectParentCategory: "اختر الفئة الأم",
subCategoryName: "اسم الفئة الفرعية",
activeSubCategory: "فئة فرعية نشطة",
updatingSubCategory: "جارٍ تحديث الفئة الفرعية...",
creatingSubCategory: "جارٍ إنشاء الفئة الفرعية...",
updateSubCategory: "تحديث الفئة الفرعية",
createSubCategory: "إنشاء الفئة الفرعية",
subcategories: "الفئات الفرعية",
parent: "الأم",
unknown: "غير معروف",
confirmDeleteSubCategory: "هل أنت متأكد أنك تريد حذف هذه الفئة الفرعية؟",
subCategoryDeleted: "تم حذف الفئة الفرعية بنجاح!",
deleteSubCategoryFailed: "فشل حذف الفئة الفرعية",
subCategoryUpdated: "تم تحديث الفئة الفرعية بنجاح!",
subCategoryCreated: "تم إنشاء الفئة الفرعية بنجاح!",
updateSubCategoryFailed: "فشل تحديث الفئة الفرعية",
createSubCategoryFailed: "فشل إنشاء الفئة الفرعية",

editCollection: "تعديل المجموعة",
addNewCollection: "إضافة مجموعة جديدة",
collectionName: "اسم المجموعة",
season: "الموسم",
year: "السنة",
collectionImage: "صورة المجموعة",
uploadCollectionImage: "رفع صورة المجموعة",
featuredCollection: "مجموعة مميزة",
activeCollection: "مجموعة نشطة",
updatingCollection: "جارٍ تحديث المجموعة...",
creatingCollection: "جارٍ إنشاء المجموعة...",
updateCollection: "تحديث المجموعة",
createCollection: "إنشاء المجموعة",
collections: "المجموعات",
confirmDeleteCollection: "هل أنت متأكد أنك تريد حذف هذه المجموعة؟",
collectionDeleted: "تم حذف المجموعة بنجاح!",
deleteCollectionFailed: "فشل حذف المجموعة",
collectionUpdated: "تم تحديث المجموعة بنجاح!",
collectionCreated: "تم إنشاء المجموعة بنجاح!",
updateCollectionFailed: "فشل تحديث المجموعة",
createCollectionFailed: "فشل إنشاء المجموعة",
cancel: "إلغاء",

// From likes/page.js
signInRequired: "تسجيل الدخول مطلوب",
signInToViewLikes: "يرجى تسجيل الدخول لعرض المنتجات المفضلة.",
likedProducts: "المنتجات المفضلة",
noLikedProducts: "لم تقم بإضافة أي منتجات إلى المفضلة بعد.",
likeProductsForLater: "أضف المنتجات التي تحبها إلى المفضلة لحفظها لوقت لاحق.",
removeFromLikesFailed: "فشل إزالة من المفضلة",
sale: "تخفيض",
sizes: "المقاسات",
more: "المزيد",

// From notifications/page.js
notifications: "الإشعارات",
manageNotifications: "إدارة إشعاراتك",
markAllAsRead: "تحديد الكل كمقروء",
noNotifications: "لا توجد إشعارات بعد",
notificationsWillAppear: "ستظهر الإشعارات هنا عندما يكون لديك تحديثات.",
justNow: "الآن",
hoursAgo: "ساعة مضت",
daysAgo: "يوم مضى",

// From orders/page.js
allOrders: "جميع الطلبات",
myOrders: "طلباتي",
noOrdersFound: "لم يتم العثور على طلبات",
noOrdersYet: "ليس لديك أي طلبات بعد",
startShopping: "ابدأ التسوق",
order: "طلب",
orders: "طلبات",
found: "تم العثور على",
placedOn: "تم الطلب في",
customer: "العميل",
customerInformation: "معلومات العميل",
name: "الاسم",
phone: "الهاتف",
address: "العنوان",
notes: "ملاحظات",
olderOrderMessage: "هذا طلب قديم. لم يتم جمع معلومات العميل في وقت الشراء.",
acceptOrder: "قبول الطلب",
rejectOrder: "رفض الطلب",
markAsShipped: "تعيين كشحن",
markAsDelivered: "تعيين كموصل",
updateOrderStatusFailed: "فشل تحديث حالة الطلب",
pending: "قيد الانتظار",
accepted: "مقبول",
rejected: "مرفوض",
shipped: "تم الشحن",
delivered: "تم التوصيل",
notProvided: "غير مقدم",

// From performance/page.js
performanceAnalytics: "تحليلات الأداء",
viewPerformanceMetrics: "عرض مقاييس أدائك",
performanceMetrics: "مقاييس الأداء",
salesPerformance: "أداء المبيعات",
userEngagement: "تفاعل المستخدم",
revenueAnalytics: "تحليلات الإيرادات",
growthMetrics: "مقاييس النمو",

// From reviews/page.js
confirmDeleteReview: "هل أنت متأكد أنك تريد حذف هذا التقييم؟",
deleteReviewFailed: "فشل حذف التقييم",
selectRating: "يرجى اختيار تقييم",
provideTitleOrComment: "يرجى تقديم عنوان أو تعليق",
reviewTitle: "عنوان التقييم",
optional: "اختياري",
summarizeExperience: "لخص تجربتك...",
yourReview: "تقييمك",
shareExperience: "شارك تجربتك مع هذا المنتج...",
characters: "حرف",
submitting: "جارٍ الإرسال...",
submitReview: "إرسال التقييم",
noReviewsYet: "لم تقم بكتابة أي تقييمات بعد",
reviewHelpShoppers: "قيم المنتجات التي اشتريتها لمساعدة المتسوقين الآخرين.",
orderNumber: "طلب رقم",
deliveredOn: "تم التوصيل في",
writeReview: "كتابة تقييم",
writeYourReview: "اكتب تقييمك",
stars: "نجوم",
star: "نجمة",
reviewedOn: "تم التقييم في",
verifiedPurchase: "شراء موثق",
submitReviewFailed: "فشل إرسال التقييم",
myReviews: "تقييماتي",
productsToReview: "المنتجات المراد تقييمها",

// From users/page.js
usersManagement: "إدارة المستخدمين",
welcomeToUsersManagement: "مرحباً بك في إدارة المستخدمين",
users: "المستخدمين",
user: "مستخدم",
email: "البريد الإلكتروني",
role: "الدور",
actions: "الإجراءات",
updating: "جارٍ التحديث...",
noUsersFound: "لم يتم العثور على مستخدمين.",
totalUsers: "إجمالي المستخدمين",
admins: "المسؤولون",
owners: "المالكون",
chefs: "الطهاة",
waiters: "النُدُل",
updatingRole: "جارٍ تحديث الدور...",

    }
  };

  const toggleLanguage = () => {
    setLanguage(prevLang => prevLang === "en" ? "ar" : "en");
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      currentLanguage: language, 
      translations: translations[language],
      toggleLanguage,
      t // Add this helper function
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};